import { expect, test } from 'claude-code/testing'

import { HAIKU, PANE, asked, choose, engine, gate, scripted, toasts, tournamentSetup } from './kit'

const START = { cwd: '.', surface: 'terminal', isInteractive: true } as const
const RUN = { command: 'chess', origin: { kind: 'composer' }, presentation: { isFullscreen: true, columns: 120 } } as const

test('resign asks first; no keeps playing, yes resigns', async ($, on) => {
  engine(on, scripted([]))
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  await ui.press({ key: 'resign' })
  expect(await ui.find({ type: 'Text', text: /Resign this game\?/ })).toBeDefined()
  await ui.press({ key: 'resign-no' })
  expect(await ui.find({ type: 'Text', text: /^Your move \((White|Black)\)$/ })).toBeDefined()
  await ui.press({ key: 'resign' })
  await ui.press({ key: 'resign-yes' })
  expect(await ui.find({ type: 'Text', text: /Black \(.+\) wins · White resigned/ })).toBeDefined()
})

test('closing mid-game asks; pause & close freezes the clock and closes', async ($, on) => {
  const clock = engine(on, scripted([]))
  const closed: string[] = []
  on('ui.close', (_$, e) => {
    closed.push(e.id)
    return { value: undefined }
  })
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'nav-settings' })
  await choose(ui, 'tc', 'Blitz 5+3')
  await ui.press({ key: 'nav-setup' })
  await ui.press({ key: 'start' })
  await ui.press({ key: 'close' })
  expect(await ui.find({ type: 'Text', text: /Leave the game\?/ })).toBeDefined()
  expect(closed).toEqual([])
  await ui.press({ key: 'close-pause' })
  expect(closed).toEqual(['chessus'])
  await clock.advance(60_000)
  expect(await ui.find({ type: 'Text', text: /Paused · p resumes/ })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: /○ You\s+5:00/ })).toBeDefined()
  await ui.press({ key: 'pause' })
  expect(await ui.find({ type: 'Text', text: /^Your move \((White|Black)\)$/ })).toBeDefined()
})

test('with the setting on, the opponent model and effort switch mid-game', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  expect(await ui.find({ key: 'opponent-model' })).toBeUndefined()
  await ui.press({ key: 'nav-settings' })
  await choose(ui, 'switch', 'Switchable from the board')
  await ui.press({ key: 'nav-setup' })
  await ui.press({ key: 'start' })
  await choose(ui, 'opponent-model', 'Haiku 4.5')
  await choose(ui, 'opponent-effort', 'max')
  await ui.input({ key: 'move', text: 'e4' })
  await clock.advance(500)
  g.release('e5')
  await clock.advance(500)
  expect(asked[0]).toBe(`${HAIKU}|max`)
  expect(await ui.find({ type: 'Text', text: /● Haiku 4\.5 \(max\)/ })).toBeDefined()
})

test('the header names the mode: casual game or tournament round', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  expect(await ui.find({ type: 'Text', text: /^CASUAL GAME$/ })).toBeDefined()
  await ui.press({ key: 'resign' })
  await ui.press({ key: 'resign-yes' })
  await tournamentSetup(ui)
  await choose(ui, 'pick-model', 'Haiku 4.5')
  await ui.press({ key: 'add' })
  await ui.press({ key: 'add' })
  await ui.press({ key: 'start-tournament' })
  await clock.advance(100)
  expect(await ui.find({ type: 'Text', text: /^TOURNAMENT #1 · ROUND 1$/ })).toBeDefined()
})

test('/chess resign needs a second step', async ($, on) => {
  engine(on, scripted([]))
  on('ui.open', () => ({ value: { isPlaced: true } }))
  await $.session.start(START)
  await $.command.run({ ...RUN, args: 'haiku low' })
  expect((await $.command.run({ ...RUN, args: 'resign' })).text).toMatch(/Run \/chess resign yes to confirm/)
  expect((await $.command.run({ ...RUN, args: 'move e4' })).text).toMatch(/You played e4/)
  expect((await $.command.run({ ...RUN, args: 'resign yes' })).text).toMatch(/You resigned\. 0-1/)
})

test('close from another screen shows its question on the board, and a new game drops any pending question', async ($, on) => {
  engine(on, scripted([]))
  on('ui.close', () => ({ value: undefined }))
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  await ui.press({ key: 'nav-settings' })
  await ui.press({ key: 'close' })
  expect(await ui.find({ type: 'Text', text: /Leave the game\?/ })).toBeDefined()
  await ui.press({ key: 'close-no' })
  await ui.press({ key: 'resign' })
  await ui.press({ key: 'nav-setup' })
  await ui.press({ key: 'start' })
  expect(await ui.find({ type: 'Text', text: /Resign this game\?/ })).toBeUndefined()
  expect(await ui.find({ type: 'Text', text: /^Your move \((White|Black)\)$/ })).toBeDefined()
})

test('a paused casual game is archived, not lost, when a tournament starts', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  await ui.input({ key: 'move', text: 'e4' })
  await clock.advance(100)
  await ui.press({ key: 'pause' })
  await tournamentSetup(ui)
  await choose(ui, 'pick-model', 'Haiku 4.5')
  await ui.press({ key: 'add' })
  await ui.press({ key: 'add' })
  await ui.press({ key: 'start-tournament' })
  expect(await ui.find({ type: 'Text', text: /Start anyway\? The current game goes to replays as unfinished/ })).toBeDefined()
  await ui.press({ key: 'replace-yes' })
  await clock.advance(100)
  await ui.press({ key: 'nav-library' })
  expect(await ui.find({ type: 'Button', text: /\* {2}abandoned$/ })).toBeDefined()
})

test('switching the opponent mid-thought drops the old reply and asks the new model', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'nav-settings' })
  await choose(ui, 'switch', 'Switchable from the board')
  await ui.press({ key: 'nav-setup' })
  await ui.press({ key: 'start' })
  await ui.input({ key: 'move', text: 'e4' })
  await clock.advance(100)
  await choose(ui, 'opponent-model', 'Haiku 4.5')
  await clock.advance(600)
  g.release('e5')
  await clock.advance(600)
  expect(asked.at(-1)).toBe(`${HAIKU}|medium`)
  expect(await ui.find({ type: 'Text', text: /^e5 / })).toBeDefined()
  expect(asked).toHaveLength(2)
})

test('/chess move plays while a replay is on screen, and a refused move leaves the view alone', async ($, on) => {
  engine(on, scripted(['e5']))
  on('ui.open', () => ({ value: { isPlaced: true } }))
  await $.session.start(START)
  await $.command.run({ ...RUN, args: 'haiku low' })
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'nav-library' })
  await ui.press({ key: 'classic-opera' })
  expect((await $.command.run({ ...RUN, args: 'move Ke2' })).text).toMatch(/not a legal move/)
  expect(await ui.find({ type: 'Text', text: /^REPLAY$/ })).toBeDefined()
  expect((await $.command.run({ ...RUN, args: 'move e4' })).text).toMatch(/You played e4/)
  expect(await ui.find({ type: 'Text', text: /^CASUAL GAME$/ })).toBeDefined()
})

test('a reply with no move in it is asked again for free; a named illegal move is penalized and quoted', async ($, on) => {
  const clock = engine(on, scripted(['Let me think about this position.', 'e5', 'Ke6']))
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  await ui.input({ key: 'move', text: 'e4' })
  for (let i = 0; i < 4; i++) await clock.advance(500)
  expect(await ui.find({ type: 'Text', text: /^e5 / })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: /illegal/ })).toBeUndefined()
  await ui.input({ key: 'move', text: 'Nf3' })
  for (let i = 0; i < 4; i++) await clock.advance(500)
  expect(await ui.find({ type: 'Text', text: /played an illegal move \("Ke6"\)/ })).toBeDefined()
})

test('save to resume puts the game under replays, and r there carries it on', async ($, on) => {
  const clock = engine(on, scripted(['e5']))
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  await ui.input({ key: 'move', text: 'e4' })
  for (let i = 0; i < 4; i++) await clock.advance(500)
  await ui.press({ key: 'save' })
  await ui.press({ key: 'save' })
  expect(toasts.at(-1)).toMatch(/Saved under replays/)
  await ui.press({ key: 'nav-library' })
  await ui.press({ key: 'lib-0' })
  expect(await ui.find({ type: 'Text', text: /^REPLAY$/ })).toBeDefined()
  await ui.press({ key: 'resume-saved' })
  await ui.press({ key: 'resume-yes' })
  expect(await ui.find({ type: 'Text', text: /^CASUAL GAME$/ })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: /^e5 / })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: /^Your move \(White\)$/ })).toBeDefined()
  await ui.press({ key: 'nav-library' })
  expect(await ui.find({ type: 'Button', text: /saved to resume/ })).toBeUndefined()
})

test('saving twice keeps one snapshot, an empty game is not saved, and resuming over a live game asks', async ($, on) => {
  const clock = engine(on, scripted(['e5', 'c5']))
  on('ui.open', () => ({ value: { isPlaced: true } }))
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  await ui.press({ key: 'save' })
  expect(toasts.at(-1)).toMatch(/Nothing to save yet/)
  await ui.input({ key: 'move', text: 'e4' })
  for (let i = 0; i < 4; i++) await clock.advance(500)
  await ui.press({ key: 'save' })
  await ui.press({ key: 'save' })
  await ui.press({ key: 'nav-library' })
  expect(await ui.findAll({ type: 'Button', text: /saved to resume/ })).toHaveLength(1)
  await ui.press({ key: 'nav-setup' })
  await ui.press({ key: 'start' })
  await ui.press({ key: 'replace-yes' })
  await ui.input({ key: 'move', text: 'd4' })
  for (let i = 0; i < 4; i++) await clock.advance(500)
  await ui.press({ key: 'nav-library' })
  const saved = (await ui.findAll({ type: 'Button', text: /saved to resume/ }))[0]!
  await ui.press({ key: saved.key! })
  await ui.press({ key: 'resume-saved' })
  expect(await ui.find({ type: 'Text', text: /Resume the saved game\?/ })).toBeDefined()
  await ui.press({ key: 'resume-yes' })
  expect(await ui.find({ type: 'Text', text: /^e5 / })).toBeDefined()
})

test('stepping to the end of a finished game shows it as ended, and a replay copies its original PGN', async ($, on) => {
  const clock = engine(on, scripted(['f6', 'g5']))
  const copied: string[] = []
  on('ui.copy', (_$, e) => {
    copied.push(e.text)
    return { value: { isCopied: true } }
  })
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  await ui.input({ key: 'move', text: 'e4' })
  for (let i = 0; i < 4; i++) await clock.advance(500)
  await ui.input({ key: 'move', text: 'd4' })
  for (let i = 0; i < 4; i++) await clock.advance(500)
  await ui.input({ key: 'move', text: 'Qh5#' })
  expect(await ui.find({ type: 'Text', text: /GAME OVER/ })).toBeDefined()
  await ui.press({ key: 'prev' })
  await ui.press({ key: 'next' })
  expect(await ui.find({ type: 'Text', text: /GAME OVER/ })).toBeDefined()
  await ui.press({ key: 'nav-library' })
  await ui.press({ key: 'classic-cardoso-fischer' })
  await ui.press({ key: 'copy' })
  expect(copied.at(-1)).toContain('[White "Rodolfo Tan Cardoso"]')
})

test('Claude spend sits in the top row: casual games say no cap, tournament games show the cap', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  expect(await ui.find({ type: 'Text', text: /^Claude \$0\.000 · no cap$/ })).toBeDefined()
  await ui.press({ key: 'resign' })
  await ui.press({ key: 'resign-yes' })
  await tournamentSetup(ui)
  await choose(ui, 'pick-model', 'Haiku 4.5')
  await ui.press({ key: 'add' })
  await ui.press({ key: 'add' })
  await ui.press({ key: 'start-tournament' })
  await clock.advance(100)
  expect(await ui.find({ type: 'Text', text: /^Claude \$0\.00 \/ \$5 cap$/ })).toBeDefined()
  await ui.press({ key: 'nav-settings' })
  expect(await ui.find({ type: 'Text', text: /^Claude \$/ })).toBeUndefined()
})
