import { expect, test } from 'claude-code/testing'

import { HAIKU, PANE, choose, engine, gate, scripted, tournamentSetup } from './kit'

const START = { cwd: '.', surface: 'terminal', isInteractive: true } as const

test('Claude vs Claude waits the spectate delay between moves', async ($, on) => {
  const clock = engine(on, scripted(['e4', 'e5', 'Nf3']))
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'nav-settings' })
  await choose(ui, 'spectate', '2s between moves')
  await ui.press({ key: 'nav-setup' })
  await choose(ui, 'white-player', 'Haiku 4.5')
  await ui.press({ key: 'start' })
  await clock.advance(100)
  expect(await ui.find({ type: 'Text', text: /e4/ })).toBeDefined()
  await clock.advance(1500)
  expect(await ui.find({ type: 'Text', text: /e5/ })).toBeUndefined()
  await clock.advance(1000)
  expect(await ui.find({ type: 'Text', text: /e5/ })).toBeDefined()
})

test('a reply that lands after a resign is dropped, and the game is saved once', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'nav-setup' })
  await ui.press({ key: 'swap' })
  await ui.press({ key: 'start' })
  await clock.advance(100)
  expect(await ui.find({ type: 'Text', text: /thinking/ })).toBeDefined()
  await ui.press({ key: 'resign' })
  await ui.press({ key: 'resign-yes' })
  g.release('e4')
  await clock.advance(1000)
  expect(await ui.find({ type: 'Text', text: /White \(.+\) wins · Black resigned/ })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: /no moves yet/ })).toBeDefined()
  await ui.press({ key: 'nav-library' })
  expect(await ui.findAll({ type: 'Button', text: /resigned/ })).toHaveLength(1)
})

test('a reply that lands after a new game started is not played in it', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'swap' })
  await ui.press({ key: 'start' })
  await clock.advance(100)
  await ui.press({ key: 'nav-setup' })
  await ui.press({ key: 'swap' })
  await ui.press({ key: 'start' })
  g.release('e4')
  await clock.advance(1000)
  expect(await ui.find({ type: 'Text', text: /^Your move \((White|Black)\)$/ })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: /no moves yet/ })).toBeDefined()
})

test('a model call that throws halts the game with a retry instead of wedging it', async ($, on) => {
  let calls = 0
  const clock = engine(on, () => {
    calls++
    if (calls === 1) throw new Error('boom')
    return 'e5'
  })
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'start' })
  for (const key of ['return', 'up', 'up', 'return']) await ui.key({ key, in: 'board' })
  for (let i = 0; i < 6; i++) await clock.advance(500)
  expect(await ui.find({ type: 'Text', text: /Press retry/ })).toBeDefined()
  expect(calls).toBe(1)
  await ui.press({ key: 'retry' })
  await clock.advance(500)
  expect(await ui.find({ type: 'Text', text: /^Your move \((White|Black)\)$/ })).toBeDefined()
})

test('a casual game cannot replace a running tournament game, and pausing freezes the clocks', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await ui.press({ key: 'nav-settings' })
  await choose(ui, 'tc', 'Blitz 3+2')
  await tournamentSetup(ui)
  await choose(ui, 'pick-model', 'Haiku 4.5')
  await ui.press({ key: 'add' })
  await ui.press({ key: 'add' })
  await ui.press({ key: 'start-tournament' })
  await clock.advance(100)
  await ui.press({ key: 'nav-setup' })
  await choose(ui, 'new-mode', 'Casual game')
  expect(await ui.find({ type: 'Text', text: /A tournament is running\. End it/ })).toBeDefined()
  await ui.press({ key: 'nav-tournament' })
  expect(await ui.find({ type: 'Text', text: /Now playing: round 1/ })).toBeDefined()

  await ui.press({ key: 'pause' })
  g.release('banana')
  await clock.advance(10 * 60_000)
  await ui.press({ key: 'nav-game' })
  expect(await ui.find({ type: 'Text', text: /Paused/ })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: /time forfeit/ })).toBeUndefined()
})

test('resuming a paused tournament re-asks Claude and the game goes on', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await tournamentSetup(ui)
  await choose(ui, 'pick-model', 'Haiku 4.5')
  await ui.press({ key: 'add' })
  await ui.press({ key: 'add' })
  await ui.press({ key: 'start-tournament' })
  await clock.advance(100)
  await ui.press({ key: 'nav-tournament' })
  await ui.press({ key: 'pause' })
  g.release('e4')
  await clock.advance(1000)
  await ui.press({ key: 'resume' })
  await clock.advance(100)
  g.release('d4')
  await clock.advance(1000)
  await ui.press({ key: 'watch' })
  expect(await ui.find({ type: 'Text', text: /d4/ })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: /e4/ })).toBeUndefined()
})

test('ending a tournament mid-game lets that game play on as a casual game', async ($, on) => {
  const g = gate()
  const clock = engine(on, g.wait)
  await $.session.start(START)
  const ui = await $.ui.mount({ plugin: 'chessus', surface: 'terminal', ...PANE })
  await tournamentSetup(ui)
  await choose(ui, 'pick-model', 'Haiku 4.5')
  await ui.press({ key: 'add' })
  await ui.press({ key: 'add' })
  await ui.press({ key: 'start-tournament' })
  await clock.advance(100)
  await ui.press({ key: 'nav-tournament' })
  await ui.press({ key: 'pause' })
  await ui.press({ key: 'stop' })
  await tournamentSetup(ui)
  expect(await ui.find({ type: 'Text', text: /ended early/ })).toBeDefined()
  g.release('e4')
  await clock.advance(1000)
  g.release('e5')
  await clock.advance(1000)
  await ui.press({ key: 'nav-game' })
  expect(await ui.find({ type: 'Text', text: /Paused/ })).toBeUndefined()
  expect(await ui.find({ type: 'Text', text: /e5/ })).toBeDefined()
})
